version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  server:
    container_name: server
    build: ./server
    ports:
      - 8080:8080
    volumes:
      - ./server:/usr/src/server

  redis:
    image: redis
    ports:
      - "6379:6379"

networks:
  default:
    driver: bridge
